// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectef;

#nullable disable

namespace projectef.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20220713224826_ModifyTaskBody")]
    partial class ModifyTaskBody
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("projectef.Models.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Age")
                        .HasMaxLength(120)
                        .HasColumnType("bigint");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasMaxLength(2)
                        .HasColumnType("real");

                    b.HasKey("AuthorId");

                    b.ToTable("Author", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("5e48e5cd-0850-48f2-9b3b-572f82f0ba91"),
                            Age = 24L,
                            Height = 1.75f,
                            Name = "Alejandro",
                            Weight = 80.2f
                        },
                        new
                        {
                            AuthorId = new Guid("656fe592-6dd1-4108-b492-c014f1faefdc"),
                            Age = 40L,
                            Height = 1.8f,
                            Name = "Josh",
                            Weight = 95.3f
                        });
                });

            modelBuilder.Entity("projectef.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("5f617470-bf19-4be4-9fea-f26a18bf616a"),
                            Description = "This is a random category creating for testing the db",
                            Importance = 20,
                            Name = "Pending Activities"
                        },
                        new
                        {
                            CategoryId = new Guid("5f617470-bf20-4be4-9fea-f26a18bf616a"),
                            Description = "This is a random category creating for testing the db",
                            Importance = 50,
                            Name = "Studying the new formulas"
                        });
                });

            modelBuilder.Entity("projectef.Models.TodoTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Task", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("b4c54026-ec34-439d-bb61-b3e4c1cb3399"),
                            AuthorId = new Guid("5e48e5cd-0850-48f2-9b3b-572f82f0ba91"),
                            CategoryId = new Guid("5f617470-bf19-4be4-9fea-f26a18bf616a"),
                            CreatedAt = new DateTime(2022, 7, 13, 17, 48, 25, 990, DateTimeKind.Local).AddTicks(8064)
                        },
                        new
                        {
                            TaskId = new Guid("b4c54026-ec34-439d-bb61-b3e4c1cb4499"),
                            AuthorId = new Guid("656fe592-6dd1-4108-b492-c014f1faefdc"),
                            CategoryId = new Guid("5f617470-bf20-4be4-9fea-f26a18bf616a"),
                            CreatedAt = new DateTime(2022, 7, 13, 17, 48, 25, 990, DateTimeKind.Local).AddTicks(8102)
                        });
                });

            modelBuilder.Entity("projectef.Models.TodoTask", b =>
                {
                    b.HasOne("projectef.Models.Author", "Author")
                        .WithMany("Tasks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectef.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("projectef.Models.Author", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("projectef.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
